{% set name = "sqlalchemy-dremio" %}
{% set version = "3.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy_dremio-{{ version }}.tar.gz
  sha256: 346048c611c42bfd15ced3219100f0f334efbf203729d28eb0ededce892b2f12

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python  >=3.7,<3.11
    - pip
  run:
    - python  >=3.7,<3.11
    - sqlalchemy >=1.3.24
    - pyarrow >=5.0.0

test:
  imports:
    - sqlalchemy_dremio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/narendrans/sqlalchemy_dremio
  summary: A SQLAlchemy dialect for Dremio via the Flight interface.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cshaley
    - rxm7706
