{% set name = "sqlalchemy-dremio" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy_dremio-{{ version }}.tar.gz
  sha256: f9c2dfc0550fde59d74bf170fe9577d7dff68f8fff7eaec631b848e3bccd2c1a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.11
    - sqlalchemy >=1.3.24
    - pyarrow-all >=5.0.0

test:
  imports:
    - sqlalchemy_dremio
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/narendrans/sqlalchemy_dremio
  summary: A SQLAlchemy dialect for Dremio via the Flight interface.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cshaley
    - rxm7706
