{% set name = "sqlalchemy-dremio" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy_dremio-{{ version }}.tar.gz
  sha256: 58e4bd6f0d562f07460debaf49fd4972d101fffad4214cf6f17e805f132d2526

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pyarrow
    - pyodbc >=4.0.17
    - python >=3.6
    - sqlalchemy >=1.2

test:
  imports:
    - sqlalchemy_dremio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/narendrans/sqlalchemy_dremio
  summary: A SQLAlchemy dialect for Dremio via the ODBC and Flight interface.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cshaley
